# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14b63db7d9e90ea3171e308029c6fd182dbbfdb89447461fcb48b232909b2a67f1e16f27bd97346d81b4835da24c76e4ef0af3b4ce83d0ac8099adb745db596

test:
  secret_key_base: a3100ae57f9be590e0bf52c54f0a20cd72e2a3c9715cd92fee88ddb3837185157c84f6fbc09114114924aa6550fbf21649b8791ce102041ac372c97123a6f460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
